#yml风格
server:
  port: 8081
logging:
  level:
    tk:
     mybatis:TRACE

spring:
  datasource:
    #url,加入ssl配置避免报错
    url: jdbc:mysql://127.0.0.1:3306/startboot?characterEncoding=UTF8&useSSL=false
    username: root
    password: buzhidao
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 5
    max-wait: 10000
    min-idle: 1
    initial-size: 3
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet.content-type: text/html
    cache: false
  http:
      encoding:
        charset: utf-8
        enabled: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.startboot.dev.pojo
